# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"actions.summerwind.dev/v1alpha1","kind":"RunnerDeployment","metadata":{"annotations":{},"name":"self-hosted-runners","namespace":"actions-runner-system"},"spec":{"replicas":1,"template":{"spec":{"organization":"somanath-dange-backstage"}}}}
  creationTimestamp: "2026-03-09T17:01:27Z"
  generation: 1
  name: self-hosted-runners
  namespace: actions-runner-system
  resourceVersion: "201399"
  uid: 35e5f3cc-54e9-45a8-ae19-b6db0ed72c31
spec:
  effectiveTime: null
  replicas: 1
  selector: null
  template:
    metadata: {}
    spec:
      dockerdContainerResources: {}
      image: ""
      organization: somanath-dange-backstage
      resources: {}
status:
  availableReplicas: 1
  desiredReplicas: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
